### ISSUE TITLE
cannot run the ppo for the benchmark

### ISSUE THREAD

**Issue by biandangan** [xtremey/ppo_compiler_gym#1]
Hi,
I try to reproduce the PPO result. But the script reports error "size mismatch for features.0.weight: copying a param with shape torch.Size([128, 57]) from checkpoint, the shape in current model is torch.Size([128, 56]).:,

I traced the ppo.py and found the parameter "steps_in_observation" is different for training and evaluation, which results different observation_space sizes. So evaluatioin cannot load the parameters.

class Evaluation:
steps_in_observation=False

Training:
steps_in_observation=True

_Traceback (most recent call last):
  File "/Users/yuanpeng/cloud/compiler/ppo/ppo.py", line 257, in <module>
    ppo_training.train(log_progress=True, training_time=60, progress_log_rate=30)
  File "/Users/yuanpeng/cloud/compiler/ppo/ppo.py", line 169, in train
    geo_maxima, geo_averages = Evaluation.evaluate(benchmarks, self.name, print_progress=False,
  File "/Users/yuanpeng/cloud/compiler/ppo/ppo.py", line 70, in evaluate
    model.load_state_dict(torch.load("models/{0}.model".format(model_name)), strict=False)
  File "/Users/yuanpeng/cloud/ENTER/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1497, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for policy_critic_network:
	size mismatch for features.0.weight: copying a param with shape torch.Size([128, 57]) from checkpoint, the shape in current model is torch.Size([128, 56])._

**Comment by ChijinZ** [comment]
Same issue. Any solution?

**Comment by sparks-code** [comment]
> Same issue. Any solution?

hello, can you reproduce the result now?

**Comment by ymahlau** [comment]
Hi,
sorry for the very late reply. This was a student project, which I did not look at in a long time. Thanks for pointing out the error! I fixed the two lines of code using the wrong argument. If you have any further questions feel free to reopen the issue. This time I enabled notifications and will see the issues earlier.
Best
Yannik
