### ISSUE TITLE
can not run ppo.py

### ISSUE THREAD

**Issue by sparks-code** [xtremey/ppo_compiler_gym#2]
when i  use python ppo.py to run the program,i meet the error. Do you know how to fix it? thank you! 
![image](https://github.com/ymahlau/ppo_compiler_gym/assets/53423567/e7cbdbe7-90b7-40c5-866f-0f1134650ba3)

**Comment by ymahlau** [comment]
Hi, sorry for the very late reply. This was a student project, which i did not look at in a long time. This is an error with your python version. In older versions, it was possible to call functions "statically" (I do not know what the proper term in python is), without creating an Evaluation object. My guess is that you are using a newer version of python. Therefore, you can either downgrade your python version, or add parentheses behind the evaluation: Evaluation().evaluate(...). Hope this helps!
Yours Yannik
